### ISSUE TITLE
Broken Link on /tokens

### ISSUE THREAD

**Issue by henrymly** [eggybytes/eggy-issues#3]
### Description

Link to "Read the SDK integration docs" is broken.

### Steps to reproduce

1. Go to useeggy.com
2. Create API token
3. Click on "Read the SDK integration docs" button

<img width="1243" alt="Screen Shot 2021-09-08 at 12 23 10 PM" src="https://user-images.githubusercontent.com/2497911/132572219-5f738f55-874a-467c-a4c0-915c4d997889.png">

### Expected behavior

User should be routed to working SDK documentation.

`https://docs.useeggy.com/` instead of `https://useeggy.com/docs`?

### Actual behavior

User is routed to "Page not found".

### Environment

* Browser: Safari Version 14.1 (16611.1.21.161.6)
* eggy SDK version: n/a

**Comment by vivianliang** [comment]
Thank you @henrymly! The fix has been deployed; closing this issue.
